#########
POST http://127.0.0.1:8000/api/auth/signup_otp_verify/
Content-Type: application/json

{

 "mobile":9837654970,
 "otp": 57746,
 "role":"owner"
    
}

#########
POST http://127.0.0.1:8000/api/auth/get_signup_otp/
Content-Type: application/json

{

    "mobile":9837654970,
    "first_name":"Anurag",
    "last_name":"Shakya"
}

##############
POST http://127.0.0.1:8000/api/initial/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTUyNjExLCJpYXQiOjE2NjE5NDkwMTEsImp0aSI6IjNjOTk1MjcxZjZiZjQ0NzFhOGU0MDk3NDQ1ZGE0MjUzIiwidXNlcl9pZCI6Nn0.tqh_3wOjuUulZo6b3aQh-ZPQ1drXnr69VIEVwIxO3n8

{ "institute_code": "afafds",
    "institute_name": "Success Point",
      "institute_desc": "DASFSFD ASF ASF",
      "max_students": "4000"
}

##############
POST http://127.0.0.1:8000/api/auth/get_login_otp/
Content-Type: application/json

{
    "mobile":"8010741981"
}


##############
POST http://127.0.0.1:8000/api/auth/login_otp_verify/
Content-Type: application/json

{
    "mobile":"9837654970",
    "otp":"36713"
}
##########
{
  "success": true,
  "message": "OTP Verified Successfully",
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTQ3MzkxLCJpYXQiOjE2NjE5NDcwOTEsImp0aSI6IjgzZDNjMWUzNDMyNzQ4Njc4ZWExMTA1ZDdjNjE2MmM5IiwidXNlcl9pZCI6Nn0.r0mUFkS8quIqm9qBP6kBeu50E8KtulsAy73b6ba3OwI",
    "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY2NDUzOTA5MSwiaWF0IjoxNjYxOTQ3MDkxLCJqdGkiOiI2Nzk4Njc2YWNjZTE0ZTZhYTQyMzM0ZjM4MmQ0OTZkNiIsInVzZXJfaWQiOjZ9.0VZKkqy3CNuxVR_WYV-gyMhCGirooAQpMMXru8NKtA8"
  },
  "status_code": 200
}



# Subject API
##############
POST http://127.0.0.1:8000/api/subject/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTU2MjQzLCJpYXQiOjE2NjE5NTI2NDMsImp0aSI6IjcwYjlkZTY4MjcxNzQ3NzhhMGI2YTQ4MmMwMTY5NWMzIiwidXNlcl9pZCI6Nn0.lAOFmES9kqYzJtn1TRP2UCNVTekef1ApsGCsThgFU-s

{
    "subject":"Maths"
}



################
# cREATING tEACHER
POST http://127.0.0.1:8000/api/auth/get_signup_otp/
Content-Type: application/json

{
    "mobile":"8010741981",
    "first_name":"Nihal",
    "last_name":"Sharma"
}


# # Otp 
# 73347


########

POST http://127.0.0.1:8000/api/auth/signup_otp_verify/
Content-Type: application/json

{
    "mobile":"8010741981",
    "otp":"73347",
    "role":"teacher"
}


#########
POST http://127.0.0.1:8000/api/initial/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTUyMTEyLCJpYXQiOjE2NjE5NDg1MTIsImp0aSI6Ijk1ZjEwNmMzOWVjMDRiMDhhMjBhNTQwYjNjMDcwNDMxIiwidXNlcl9pZCI6N30.cdKzYNQfUsbs0e6xpKDWcTuP2-v3B9JNTMGN-f4XXEo

{
    "institute_code":"afafds"
}



#########
POST http://127.0.0.1:8000/api/subject/assign_subjects/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYxOTU2MjQzLCJpYXQiOjE2NjE5NTI2NDMsImp0aSI6IjcwYjlkZTY4MjcxNzQ3NzhhMGI2YTQ4MmMwMTY5NWMzIiwidXNlcl9pZCI6Nn0.lAOFmES9kqYzJtn1TRP2UCNVTekef1ApsGCsThgFU-s

{
    "teacher_id":"7",
    "grades":["11"],
    "subjects":["Maths"]

}




