# Generated by Django 4.1 on 2022-10-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0013_institute_teachers'),
        ('batch', '0004_document_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='institute.institute'),
        ),
    ]
