# Generated by Django 4.0.6 on 2022-08-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalbatch_teacher_remove_batch_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbatch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='historicalinstitute',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinstitute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='historicalteacherrequest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalteacherrequest',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='historicalteacherrequest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherrequest',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='teacherrequest',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='HistoricalBatch',
        ),
        migrations.DeleteModel(
            name='HistoricalInstitute',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentRequest',
        ),
        migrations.DeleteModel(
            name='HistoricalTeacherRequest',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='StudentRequest',
        ),
        migrations.DeleteModel(
            name='TeacherRequest',
        ),
    ]
