# Generated by Django 4.0.6 on 2022-08-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_historicalbatch_history_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudentprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalteacherprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalteacherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalOwnerProfile',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentProfile',
        ),
        migrations.DeleteModel(
            name='HistoricalTeacherProfile',
        ),
        migrations.DeleteModel(
            name='OwnerProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
