# Generated by Django 4.0.6 on 2022-08-11 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0002_teacherprofile_studentprofile_ownerprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_class',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='batch_class',
        ),
        migrations.AddField(
            model_name='batch',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbatch',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='institute',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.institute')),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.subject'),
        ),
        migrations.AlterField(
            model_name='historicalbatch',
            name='batch_subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institute.subject'),
        ),
    ]
