# Generated by Django 4.0.6 on 2022-08-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_remove_batch_batch_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='teachers',
        ),
        migrations.AddField(
            model_name='historicalteacherprofile',
            name='institute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institute.institute'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='institute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='institute.institute'),
            preserve_default=False,
        ),
    ]
