# Generated by Django 4.0.6 on 2022-08-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_remove_institute_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='aaf', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
