# Generated by Django 4.0.6 on 2022-08-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_remove_subject_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudentprofile',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalstudentprofile',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
