# Generated by Django 4.0.6 on 2022-08-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_batch_blocklist_alter_batch_students_subjectaccess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbatch',
            name='batch_subject',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='historicalbatch',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstudentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='HistoricalBatch',
        ),
        migrations.DeleteModel(
            name='HistoricalStudentRequest',
        ),
        migrations.DeleteModel(
            name='StudentRequest',
        ),
    ]
