# Generated by Django 4.0.6 on 2022-09-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_historicalownerprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteacherprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='about_me',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
