# Generated by Django 4.0.6 on 2022-09-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_historicalteacherprofile_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalteacherprofile',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='institute',
        ),
    ]
