# Generated by Django 4.1 on 2022-10-16 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institute', '0012_remove_historicalteacherprofile_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='teachers',
            field=models.ManyToManyField(related_name='institutes', to=settings.AUTH_USER_MODEL),
        ),
    ]
